//! Vitrine — a fast, focused, catalog-aware image browser + reviewer for GNOME.
//!
//! Phase 0: an empty-but-real application. Registers the compiled GResource,
//! starts an `adw::Application`, and presents a composite-template
//! `AdwApplicationWindow` with a headerbar and About dialog. The browser grid,
//! viewer, filmstrip, index and dedup layers land in later phases (see PLAN.md).

mod decode;
mod grid_cell;
mod image_object;
mod thumbnails;
mod window;

mod config {
    // Generated by build.rs (see config.rs.in). Some constants are consumed by
    // later phases; allow them ahead of use.
    #![allow(dead_code)]
    include!(concat!(env!("OUT_DIR"), "/config.rs"));
}

use adw::prelude::*;
use gtk::{gio, glib};

use crate::window::VitrineWindow;

fn main() -> glib::ExitCode {
    // i18n plumbing from commit one. No catalogs exist yet; this registers the
    // text domain so the Blueprint `_()` strings translate once po/ fills in —
    // retrofitting later is miserable.
    gettextrs::setlocale(gettextrs::LocaleCategory::LcAll, "");
    gettextrs::bindtextdomain(config::GETTEXT_PACKAGE, config::LOCALEDIR).expect("bindtextdomain");
    gettextrs::bind_textdomain_codeset(config::GETTEXT_PACKAGE, "UTF-8")
        .expect("bind_textdomain_codeset");
    gettextrs::textdomain(config::GETTEXT_PACKAGE).expect("textdomain");

    // Load the compiled gresource bundle (window.ui, style.css) from the install
    // pkgdatadir under Meson, or OUT_DIR under a plain `cargo` build (see build.rs).
    let gresource_path = format!("{}/vitrine.gresource", config::PKGDATADIR);
    let resource = gio::Resource::load(&gresource_path)
        .unwrap_or_else(|e| panic!("failed to load gresource at {gresource_path}: {e}"));
    gio::resources_register(&resource);

    let app = adw::Application::builder()
        .application_id(config::APP_ID)
        .flags(gio::ApplicationFlags::HANDLES_OPEN)
        .build();

    app.connect_startup(|app| {
        setup_actions(app);
        load_css();
    });
    app.connect_activate(|app| present(&window_for(app)));
    app.connect_open(|app, files, _hint| {
        let window = window_for(app);
        if let Some(file) = files.first() {
            window.open_location(file.clone());
        }
        present(&window);
    });

    app.run()
}

fn window_for(app: &adw::Application) -> VitrineWindow {
    app.active_window()
        .and_downcast::<VitrineWindow>()
        .unwrap_or_else(|| VitrineWindow::new(app))
}

fn present(window: &VitrineWindow) {
    // Fully qualified: adw::prelude globs several traits that each define
    // `present()`, so a bare method call is ambiguous.
    gtk::prelude::GtkWindowExt::present(window);
}

fn load_css() {
    let provider = gtk::CssProvider::new();
    provider.load_from_resource(&format!("{}/style.css", config::GRESOURCE_PREFIX));
    if let Some(display) = gtk::gdk::Display::default() {
        gtk::style_context_add_provider_for_display(
            &display,
            &provider,
            gtk::STYLE_PROVIDER_PRIORITY_APPLICATION,
        );
    }
}

fn setup_actions(app: &adw::Application) {
    let about = gio::SimpleAction::new("about", None);
    about.connect_activate(glib::clone!(
        #[weak]
        app,
        move |_, _| {
            let window = app.active_window();
            adw::AboutDialog::builder()
                .application_name("Vitrine")
                .application_icon(config::APP_ID)
                .version(config::VERSION)
                .developer_name("Miguel Almanzar")
                .license_type(gtk::License::Gpl30)
                // Proves the app↔engine link is real end-to-end in Phase 0.
                .debug_info(format!("engine {}", vitrine_engine::VERSION))
                .build()
                .present(window.as_ref());
        }
    ));
    app.add_action(&about);
    app.set_accels_for_action("app.about", &["F1"]);
    app.set_accels_for_action("window.close", &["<Ctrl>w"]);
}
